'use client';
import {useEffect,useState} from 'react';
import * as github from '@/lib/github';
import {BarChart3,Plus,Search,CalendarDays,CheckCheck,Layers3,SlidersHorizontal,Database,Check,Trash2,FolderKanban,Clock3,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {RequirementsPanel} from '@/components/requirements-panel';
import {PlanEditor} from '@/components/plan-editor';
import {Project,stages,progress,createDefaultTasks,createDefaultMilestones,normalizeProject} from '@/lib/projects';
function Pick({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
const date=(s:string)=>s?new Date(s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}):'No due date';
export default function Home({onLogout}:{onLogout:()=>void}){
 const [sync,setSync]=useState(github.state());
 useEffect(()=>github.subscribe(()=>setSync({...github.state()})),[]);
 const [projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[tab,setTab]=useState('All projects'),[stage,setStage]=useState('All stages'),[draft,setDraft]=useState<Project|null>(null),[saving,setSaving]=useState(false),[requirementsBusy,setRequirementsBusy]=useState(false),[deleting,setDeleting]=useState(false);
 async function load(discard=false){setLoading(true);setError('');try{await github.refresh(discard);setProjects(github.projects());}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{setProjects(github.projects());setLoading(false);const update=()=>setProjects(github.projects());const off=github.subscribe(update);const refresh=()=>{github.refresh().catch(()=>{});};window.addEventListener('online',refresh);window.addEventListener('focus',refresh);const interval=setInterval(refresh,60000);return()=>{off();window.removeEventListener('online',refresh);window.removeEventListener('focus',refresh);clearInterval(interval)}},[]);
 const active=projects.filter(p=>p.stage!=='Deployed');const today=new Date().toLocaleDateString('en-CA');const overdue=active.filter(p=>p.due&&p.due<today);const done=projects.filter(p=>p.stage==='Deployed');
 const filtered=projects.filter(p=>(tab!=='In progress'||p.stage!=='Deployed')&&(tab!=='Completed'||p.stage==='Deployed')&&(stage==='All stages'||p.stage===stage)&&`${p.name} ${p.owner} ${p.source}`.toLowerCase().includes(query.toLowerCase()));
 const upcomingMilestones=projects.flatMap(p=>p.milestones.filter(m=>!m.done&&m.due).map(m=>({...m,project:p}))).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,3);
 const dueSoon=[...active].filter(p=>p.due).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4);
 function open(p:Project){setDraft(structuredClone(p));setDeleting(false)}
 function create(){open({id:crypto.randomUUID(),name:'',description:'',owner:'Roah',due:'',stage:stages[0],priority:'Medium',source:'',sample:false,tasks:createDefaultTasks(),milestones:createDefaultMilestones()})}
 async function save(){if(!draft)return;setSaving(true);try{await github.saveProject(draft);setProjects(github.projects());setDraft(null);toast.success(github.state().pending?'Saved in browser; will sync when connected':'Project saved to private GitHub JSON');}catch(e){setProjects(github.projects());toast.error((e as Error).message)}finally{setSaving(false)}}
 async function remove(){if(!draft)return;setSaving(true);try{await github.deleteProject(draft.id);setProjects(github.projects());setDraft(null);toast.success(github.state().pending?'Deleted locally; waiting to sync':'Project deleted')}catch(e){setProjects(github.projects());toast.error((e as Error).message)}finally{setSaving(false)}}
 async function backupImport(file:File){if(!window.confirm('Replace all projects and requirements with this backup? Export your current backup first if needed.'))return;setLoading(true);try{await github.importBackup(file);setProjects(github.projects());toast.success('Backup imported')}catch(e){toast.error((e as Error).message)}finally{setLoading(false)}}
 const update=(key:keyof Project,value:any)=>setDraft(p=>p?{...p,[key]:value}:p);
 return <div className="app"><Toaster richColors/><header className="topbar"><a className="brand" href={import.meta.env.BASE_URL} aria-label="BI Studio home"><span className="brand-icon"><BarChart3 size={23}/></span>BI Studio<span className="brand-divider"/> <span className="workspace-name">Project workspace</span></a><div className="top-right"><span className="private-label">Personal workspace</span><button className="secondary" onClick={onLogout} disabled={saving||requirementsBusy||sync.busy}>Sign out</button></div></header>
 <main><div className="sync-toolbar"><span role="status" className={sync.pending?'sync-pending':''}>{sync.message}</span><div><button type="button" className="secondary" disabled={saving||requirementsBusy||sync.busy} onClick={()=>{if(!github.state().pending||window.confirm('Discard unsynced browser changes and load the GitHub copy? Export backup first to keep them.'))load(github.state().pending)}}>Reload GitHub</button><button className="secondary" onClick={github.exportBackup}>Export backup</button><label className="secondary import-button">Import backup<input type="file" accept=".json,application/json" disabled={loading||saving||requirementsBusy||sync.busy} onChange={e=>{const f=e.target.files?.[0];if(f)backupImport(f);e.target.value='';}}/></label></div></div><div className="page-heading"><div><div className="eyebrow">WORKSPACE / OVERVIEW</div><h1>Dashboard projects<span className="title-dot">.</span></h1><p>From the first requirement to the final report.</p></div><button className="primary" onClick={create} disabled={loading||!!error}><Plus size={18}/>New project</button></div>
 <section className="stats" aria-label="Project summary">{[{label:'Total projects',value:projects.length,icon:FolderKanban,caption:'Across your workspace'},{label:'In progress',value:active.length,icon:Layers3,caption:'Moving toward delivery'},{label:'Completed',value:done.length,icon:CheckCheck,caption:'Dashboards deployed'},{label:'Overdue',value:overdue.length,icon:Clock3,caption:'Open projects past due'}].map((s,i)=><div className={'stat stat-'+i} key={s.label}><div className="stat-title">{s.label}<s.icon size={18}/></div><div className="stat-number">{loading?'—':s.value.toString().padStart(2,'0')}</div><span>{s.caption}</span></div>)}</section>
 <section className="pipeline"><div className="pipeline-title"><span className="eyebrow">DELIVERY PIPELINE</span><span>One step closer to insight</span></div><div className="pipeline-stages">{stages.map((s,i)=><button key={s} className={stage===s?'selected':''} onClick={()=>setStage(stage===s?'All stages':s)}><span className="stage-number">0{i+1}</span><span>{s}<strong>{projects.filter(p=>p.stage===s).length}</strong></span><div className="stage-line" style={{background:['#c4cfce','#a8bebd','#7caaa5','#498b83','#266c61','#c4d967'][i]}}/></button>)}</div></section>
 <div className="content-grid"><section className="projects-section"><div className="section-heading"><h2>Your projects <span>{projects.length}</span></h2><span className="subtle">Power BI portfolio</span></div><div className="tools"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="All projects">All projects</TabsTrigger><TabsTrigger value="In progress">In progress</TabsTrigger><TabsTrigger value="Completed">Completed</TabsTrigger></TabsList></Tabs><label className="search"><Search size={17}/><input placeholder="Search projects..." value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search projects"/></label></div><div className="filter-row"><div><SlidersHorizontal size={15}/><Pick value={stage} onChange={setStage} items={['All stages',...stages]} label="Filter stage"/></div><span>{filtered.length} projects{projects.some(p=>p.sample)?' · Includes sample projects':''}</span></div>
 {error?<div className="empty" role="alert"><h3>Workspace unavailable</h3><p>{error}</p><button onClick={()=>load()} className="primary">Retry</button></div>:loading?<div className="cards">{[1,2,3,4].map(n=><Skeleton key={n} className="h-64 rounded-xl"/>)}</div>:filtered.length===0?<div className="empty"><FolderKanban size={36}/><h3>{projects.length?'No matching projects':'A fresh start for your next dashboard'}</h3><p>{projects.length?'Try another search or delivery stage.':'Create a project to start tracking delivery.'}</p><button className="secondary" onClick={()=>{setQuery('');setStage('All stages');setTab('All projects');if(!projects.length)create()}}>{projects.length?'Clear filters':'Create project'}</button></div>:<div className="cards">{filtered.map((p,i)=><button className="project-card" key={p.id} onClick={()=>open(p)}><div className="card-top"><span className={'project-icon color-'+stages.indexOf(p.stage)}><BarChart3 size={22}/></span><span className={'priority '+p.priority.toLowerCase()}>{p.priority} priority</span></div><div className="card-name">{p.name}</div><p className="description">{p.description||'Add a description for this dashboard.'}</p><div className="source"><Database size={13}/>{p.source||'Source not set'}{p.sample&&<small>Sample</small>}</div><div className="card-progress"><span>{p.stage}</span><strong>{progress(p)}%</strong></div><Progress value={progress(p)} aria-label={`${p.name} task completion`}/><div className="milestone-summary">{p.milestones.filter(m=>m.done).length}/{p.milestones.length} milestones completed</div><div className="card-footer"><span><span className="mini-avatar">{p.owner?p.owner.split(' ').map(x=>x[0]).join('').slice(0,2):'?'}</span>{p.owner||'Unassigned'}</span><span className={p.due&&p.due<today&&p.stage!=='Deployed'?'late':''}><CalendarDays size={14}/>{date(p.due)}</span></div></button>)}</div>}</section>
 <aside><section className="upcoming"><div className="section-heading"><h2>On the horizon</h2><CalendarDays size={18}/></div><p className="aside-description">Your next project deadlines</p>{dueSoon.length?dueSoon.map(p=><button className="deadline" key={p.id} onClick={()=>open(p)}><span className="date-block"><small>{new Date(p.due+'T12:00:00').toLocaleDateString('en-US',{month:'short'})}</small><strong>{p.due.slice(8)}</strong></span><span><b>{p.name}</b><small>{p.stage}</small></span></button>):<p className="aside-description">No upcoming deadlines.</p>}</section><section className="upcoming milestone-horizon"><div className="section-heading"><h2>Upcoming milestones</h2></div>{upcomingMilestones.length?upcomingMilestones.map(m=><button className="deadline" key={m.project.id+m.id} onClick={()=>open(m.project)}><span className="date-block"><small>{new Date(m.due+'T12:00:00').toLocaleDateString('en-US',{month:'short'})}</small><strong>{m.due.slice(8)}</strong></span><span><b>{m.title}</b><small>{m.project.name}</small></span></button>):<p className="aside-description">Add milestone dates inside a project to see them here.</p>}</section></aside></div>
 <footer><span><BarChart3 size={15}/> BI Studio</span><span>Build with clarity. Deliver with confidence.</span></footer></main>
 <Dialog open={!!draft} onOpenChange={v=>{if(!v&&!saving&&!requirementsBusy)setDraft(null)}}><DialogContent className="project-dialog">{draft&&<><DialogTitle>{projects.some(p=>p.id===draft.id)?'Project details':'Create a project'}</DialogTitle><DialogDescription>Plan the work and track your dashboard delivery.</DialogDescription><form onSubmit={e=>{e.preventDefault();save()}}><div className="form-fields"><label>Project name<input autoFocus required maxLength={180} value={draft.name} onChange={e=>update('name',e.target.value)} placeholder="e.g. Sales performance dashboard"/></label><label>Description<textarea value={draft.description} onChange={e=>update('description',e.target.value)} placeholder="What will this dashboard help people decide?"/></label><div className="form-two"><label>Owner<input value={draft.owner} onChange={e=>update('owner',e.target.value)} placeholder="Project owner"/></label><label>Due date<input type="date" value={draft.due} onChange={e=>update('due',e.target.value)}/></label><label>Delivery stage<Pick value={draft.stage} onChange={v=>update('stage',v)} items={stages} label="Delivery stage"/></label><label>Priority<Pick value={draft.priority} onChange={v=>update('priority',v)} items={['Low','Medium','High']} label="Priority"/></label></div><label>Data sources<input value={draft.source} onChange={e=>update('source',e.target.value)} placeholder="e.g. Oracle, SharePoint, Excel"/></label><RequirementsPanel project={draft} savedProject={projects.find(p=>p.id===draft.id)} onBusy={setRequirementsBusy}/><PlanEditor project={draft} onChange={setDraft}/></div><div className="form-actions">{projects.some(p=>p.id===draft.id)&&<button className="delete" type="button" onClick={()=>setDeleting(!deleting)} disabled={saving||requirementsBusy}><Trash2 size={16}/>Delete</button>}<button type="button" className="secondary" disabled={saving||requirementsBusy} onClick={()=>setDraft(null)}>Cancel</button><button className="primary" disabled={saving||requirementsBusy}>{saving?'Saving...':'Save project'}</button></div>{deleting&&<div className="delete-confirm"><span>Delete this project and its tasks?</span><button type="button" disabled={saving||requirementsBusy} onClick={remove}>Yes, delete project</button><button type="button" onClick={()=>setDeleting(false)}>Keep project</button></div>}</form></>}</DialogContent></Dialog>
 </div>
}
