'use client';
import {useState} from 'react';
import {Plus,X,Flag} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Project,Task,taskDone,progress,completion} from '@/lib/projects';
export function PlanEditor({project:p,onChange}:{project:Project;onChange:(p:Project)=>void}){
 const [taskTitle,setTaskTitle]=useState(''),[subTitles,setSubTitles]=useState<Record<string,string>>({}),[milestoneTitle,setMilestoneTitle]=useState('');
 const c=completion(p);
 function changeTask(id:string,change:Partial<Task>){onChange({...p,tasks:p.tasks.map(t=>{if(t.id!==id)return t;const next={...t,...change};return {...next,done:taskDone(next)}})});}
 function addSub(id:string){const title=subTitles[id]?.trim();if(!title)return;const t=p.tasks.find(t=>t.id===id)!;changeTask(id,{subtasks:[...t.subtasks,{id:crypto.randomUUID(),title,done:false}]});setSubTitles(v=>({...v,[id]:''}));}
 function addTask(){if(!taskTitle.trim())return;onChange({...p,tasks:[...p.tasks,{id:crypto.randomUUID(),title:taskTitle.trim(),done:false,subtasks:[]}]});setTaskTitle('');}
 function addMilestone(){if(!milestoneTitle.trim())return;onChange({...p,milestones:[...p.milestones,{id:crypto.randomUUID(),title:milestoneTitle.trim(),due:'',done:false}]});setMilestoneTitle('');}
 return <section className="plan-editor"><div className="task-heading"><h3>Tasks & subtasks</h3><span>{progress(p)}% complete</span></div><p className="plan-help">Default Power BI delivery tasks. Expand a task to manage its subtasks.</p><Progress value={progress(p)} aria-label="Project task completion"/><div className="plan-count">{p.tasks.filter(taskDone).length}/{p.tasks.length} tasks · {c.done}/{c.total} work items complete</div>
 <Accordion type="multiple" className="task-groups">{p.tasks.map(t=><AccordionItem value={t.id} key={t.id}><div className="task-group-header"><Checkbox aria-label={'Complete all: '+t.title} checked={taskDone(t)?true:t.subtasks.some(s=>s.done)?'indeterminate':false} onCheckedChange={v=>changeTask(t.id,{done:v===true,subtasks:t.subtasks.map(s=>({...s,done:v===true}))})}/><AccordionTrigger><span>{t.title}</span><span className="subtask-count">{t.subtasks.filter(s=>s.done).length}/{t.subtasks.length}</span></AccordionTrigger></div><AccordionContent><div className="task-edit"><input aria-label="Task title" required maxLength={300} value={t.title} onChange={e=>changeTask(t.id,{title:e.target.value})}/><button type="button" className="remove-item" aria-label={'Remove task '+t.title} onClick={()=>onChange({...p,tasks:p.tasks.filter(x=>x.id!==t.id)})}><X size={17}/></button></div><div className="subtasks">{t.subtasks.map(s=><div className="subtask-row" key={s.id}><Checkbox aria-label={'Complete '+s.title} checked={s.done} onCheckedChange={v=>changeTask(t.id,{subtasks:t.subtasks.map(x=>x.id===s.id?{...x,done:v===true}:x)})}/><input aria-label="Subtask title" className={s.done?'completed-title':''} required maxLength={300} value={s.title} onChange={e=>changeTask(t.id,{subtasks:t.subtasks.map(x=>x.id===s.id?{...x,title:e.target.value}:x)})}/><button type="button" className="remove-item" aria-label={'Remove subtask '+s.title} onClick={()=>changeTask(t.id,{subtasks:t.subtasks.filter(x=>x.id!==s.id)})}><X size={15}/></button></div>)}{!t.subtasks.length&&<p className="plan-help">Add subtasks to break down this task.</p>}<div className="add-task"><input aria-label={'New subtask for '+t.title} placeholder="Add a subtask..." maxLength={300} value={subTitles[t.id]||''} onChange={e=>setSubTitles(v=>({...v,[t.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSub(t.id)}}}/><button type="button" className="secondary" disabled={!subTitles[t.id]?.trim()} onClick={()=>addSub(t.id)}><Plus size={16}/>Add</button></div></div></AccordionContent></AccordionItem>)}</Accordion>
 <div className="add-task"><input aria-label="New task" placeholder="Add a custom task..." maxLength={300} value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addTask()}}}/><button type="button" className="secondary" disabled={!taskTitle.trim()} onClick={addTask}><Plus size={16}/>Task</button></div>
 <div className="task-heading milestone-heading"><h3><Flag size={17}/>Milestones</h3><span>{p.milestones.filter(m=>m.done).length}/{p.milestones.length} achieved</span></div><p className="plan-help">Set target dates and mark key deliverables achieved. Milestones are tracked separately from task progress.</p><div className="milestone-list">{p.milestones.map(m=><div className="milestone-item" key={m.id}><Checkbox aria-label={'Achieved: '+m.title} checked={m.done} onCheckedChange={v=>onChange({...p,milestones:p.milestones.map(x=>x.id===m.id?{...x,done:v===true}:x)})}/><input className={m.done?'completed-title':''} aria-label="Milestone title" required maxLength={300} value={m.title} onChange={e=>onChange({...p,milestones:p.milestones.map(x=>x.id===m.id?{...x,title:e.target.value}:x)})}/><input type="date" aria-label={'Target date for '+m.title} value={m.due} onChange={e=>onChange({...p,milestones:p.milestones.map(x=>x.id===m.id?{...x,due:e.target.value}:x)})}/><button type="button" className="remove-item" aria-label={'Remove milestone '+m.title} onClick={()=>onChange({...p,milestones:p.milestones.filter(x=>x.id!==m.id)})}><X size={15}/></button></div>)}</div><div className="add-task"><input aria-label="New milestone" placeholder="Add a milestone..." maxLength={300} value={milestoneTitle} onChange={e=>setMilestoneTitle(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addMilestone()}}}/><button type="button" className="secondary" disabled={!milestoneTitle.trim()} onClick={addMilestone}><Plus size={16}/>Milestone</button></div></section>
}
