import {type Project,isDate,localDate,portfolioSummary} from './projects';
import {executiveRows} from './executive';
const xml=(value:string)=>value.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const textCell=(ref:string,value:string,style=0)=>`<c r="${ref}" t="inlineStr" s="${style}"><is><t xml:space="preserve">${xml(value)}</t></is></c>`;
const numberCell=(ref:string,value:number,style=0)=>`<c r="${ref}" s="${style}"><v>${value}</v></c>`;
const dateCell=(ref:string,value:string)=>isDate(value)?numberCell(ref,Math.round(Date.parse(value+'T00:00:00Z')/86400000)+25569,3):textCell(ref,'—');
const row=(n:number,cells:string,height?:number)=>`<row r="${n}"${height?` ht="${height}" customHeight="1"`:''}>${cells}</row>`;
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
// XLSX is a ZIP of XML files. Store entries without compression for a small,
// dependency-free browser export, with CRC32 and a standard central directory.
function zip(files:Record<string,string>):Uint8Array{
 const encoder=new TextEncoder();const table=new Uint32Array(256);
 for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0;}
 const crc=(bytes:Uint8Array)=>{let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
 const chunks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;
 for(const [name,content] of Object.entries(files)){
  const filename=encoder.encode(name),data=encoder.encode(content),checksum=crc(data);
  const header=new Uint8Array(30+filename.length);const h=new DataView(header.buffer);
  h.setUint32(0,0x04034b50,true);h.setUint16(4,20,true);h.setUint16(6,0x800,true);h.setUint16(12,0x21,true);h.setUint32(14,checksum,true);h.setUint32(18,data.length,true);h.setUint32(22,data.length,true);h.setUint16(26,filename.length,true);header.set(filename,30);
  const directory=new Uint8Array(46+filename.length);const d=new DataView(directory.buffer);
  d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint16(14,0x21,true);d.setUint32(16,checksum,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,filename.length,true);d.setUint32(42,offset,true);directory.set(filename,46);
  chunks.push(header,data);central.push(directory);offset+=header.length+data.length;
 }
 const centralSize=central.reduce((s,c)=>s+c.length,0);const end=new Uint8Array(22);const e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,central.length,true);e.setUint16(10,central.length,true);e.setUint32(12,centralSize,true);e.setUint32(16,offset,true);
 const out=new Uint8Array(offset+centralSize+22);let at=0;for(const c of [...chunks,...central,end]){out.set(c,at);at+=c.length;}return out;
}
export function buildExecutiveWorkbook(projects:Project[],today=localDate()):Uint8Array{
 const departments=executiveRows(projects,today),totals=portfolioSummary(projects,today);
 const summaryRows=[row(1,textCell('A1','BI Studio | Executive Summary',1),30),row(2,textCell('A2',`As of ${today}`)),row(4,textCell('A4','Portfolio metric',2)+textCell('B4','Projects',2)),...totals.map((t,i)=>row(i+5,textCell(`A${i+5}`,t.label)+numberCell(`B${i+5}`,t.value))),row(11,textCell('A11','Departments represented')+numberCell('B11',departments.length)),row(13,textCell('A13','Overdue also counts within Not Yet Started or In Progress.',4),32),row(15,textCell('A15','Red: at least one unfinished project is overdue.',4),32),row(16,textCell('A16','Amber: unfinished work is not started, has no finish date, or is due within seven days.',4),40),row(17,textCell('A17','Green: all work is completed, or unfinished work is due more than seven days away.',4),40)].join('');
 const summary=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="19"/><cols><col min="1" max="1" width="64" customWidth="1"/><col min="2" max="2" width="18" customWidth="1"/></cols><sheetData>${summaryRows}</sheetData><mergeCells count="5"><mergeCell ref="A1:B1"/><mergeCell ref="A13:B13"/><mergeCell ref="A15:B15"/><mergeCell ref="A16:B16"/><mergeCell ref="A17:B17"/></mergeCells></worksheet>`;
 const headings=['Department','Scope','Start','Finish','Status (RAG)'];
 const portfolioRows=[row(1,textCell('A1','BI Studio | Department Portfolio',1),30),row(2,textCell('A2',`Department-level summary · As of ${today}`)),row(3,headings.map((v,i)=>textCell(`${String.fromCharCode(65+i)}3`,v,2)).join(''),24),...departments.map((r,i)=>{const n=i+4;return row(n,textCell(`A${n}`,r.department,4)+textCell(`B${n}`,r.scope,4)+dateCell(`C${n}`,r.start)+dateCell(`D${n}`,r.finish)+textCell(`E${n}`,`${r.status} (${r.color})`,r.color==='Red'?5:r.color==='Amber'?6:7),45);})].join('');
 const last=departments.length+3;
 const portfolio=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><sheetViews><sheetView workbookViewId="0"><pane ySplit="3" topLeftCell="A4" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="20"/><cols><col min="1" max="1" width="25" customWidth="1"/><col min="2" max="2" width="80" customWidth="1"/><col min="3" max="4" width="18" customWidth="1"/><col min="5" max="5" width="30" customWidth="1"/></cols><sheetData>${portfolioRows}</sheetData><autoFilter ref="A3:E${last}"/><mergeCells count="2"><mergeCell ref="A1:E1"/><mergeCell ref="A2:E2"/></mergeCells><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="9" fitToWidth="1" fitToHeight="0"/></worksheet>`;
 const styles=`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="${ns}"><numFmts count="1"><numFmt numFmtId="164" formatCode="dd mmm yyyy"/></numFmts><fonts count="6"><font><sz val="11"/><color rgb="FF233634"/><name val="Calibri"/></font><font><b/><sz val="16"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FF365B43"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFA4473B"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FF89691E"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FF327550"/><name val="Calibri"/></font></fonts><fills count="7"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1E3934"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEDF3EB"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFF0EC"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFF6DF"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEAF5EC"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="8"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="3" borderId="0" xfId="0"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf><xf numFmtId="0" fontId="3" fillId="4" borderId="0" xfId="0"/><xf numFmtId="0" fontId="4" fillId="5" borderId="0" xfId="0"/><xf numFmtId="0" fontId="5" fillId="6" borderId="0" xfId="0"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 return zip({
  '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>',
  '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
  'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Executive Summary" sheetId="1" r:id="rId1"/><sheet name="Department Portfolio" sheetId="2" r:id="rId2"/></sheets></workbook>`,
  'xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
  'xl/styles.xml':styles,'xl/worksheets/sheet1.xml':summary,'xl/worksheets/sheet2.xml':portfolio,
 });
}
export function exportExecutiveExcel(projects:Project[],today=localDate()){
 const bytes=buildExecutiveWorkbook(projects,today);const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));
 const a=document.createElement('a');a.href=url;a.download=`BI-Studio-Executive-${today}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
